// Auto-generated theorem tools for inference-forms-mcp
// 115 new tools from FORMAL_LEDGER.md

export const LEDGER_TOOL_DEFINITIONS = [
  {
    name: 'thm_hole_positive_weight',
    description: 'A structural hole always has strictly positive interpolation weight. The complement distribution never assigns zero probability to any hole. Never say never in prediction [LEDGER: THM-HOLE-POSITIVE-WEIGHT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_interpolation_bounded',
    description: 'The interpolation weight is bounded between 1 and rounds + 1. The prediction is always finite and within the Buleyean weight range [LEDGER: THM-INTERPOLATION-BOUNDED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rejection_reduces_prediction',
    description: 'More neighbor rejection = lower prediction weight. Structure constrains: neighbors rejection data shapes the holes complement distribution [LEDGER: THM-REJECTION-REDUCES-PREDICTION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_lattice_partition',
    description: 'The lattice is exactly partitioned into observed positions and holes. observedCount + holeCount = totalPositions. Conservation law of the structural lattice [LEDGER: THM-LATTICE-PARTITION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_neighbor_dominates_uninformed',
    description: 'Structural prediction with neighbor data is at least as informative as uninformed guessing. Interpolation weight <= uninformed weight. Structure provides signal [LEDGER: THM-NEIGHBOR-DOMINATES-UNINFORMED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_strict_dominance',
    description: 'With nontrivial neighbor rejection (neighborVoidSum > 0), structural prediction is strictly more informative than guessing. The gap equals min(voidSum, roundsSum) [LEDGER: THM-STRICT-DOMINANCE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_holes_ordered',
    description: 'Two holes with different neighbor rejection receive different predictions. The lattice differentiates. Formalizes: "gallium is more like aluminum than iron" [LEDGER: THM-HOLES-ORDERED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_mendeleev_is_complement',
    description: 'Mendeleevs interpolation method is isomorphic to computing the Buleyean complement weight from neighbor-aggregated void boundary. Same formula: rounds - min(void, rounds) + 1 [LEDGER: THM-MENDELEEV-IS-COMPLEMENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_algebraic_hole_is_void_gap',
    description: 'Algebraic holes (Diracs positron, Paulis neutrino) are positions demanded by lattice partition conservation. The lattice forces the hole to exist; the complement distribution predicts its properties [LEDGER: THM-ALGEBRAIC-HOLE-IS-VOID-GAP]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_non_empirical_solomonoff',
    description: 'Non-empirical prediction composes with Solomonoff prediction. Holes in simpler lattices get higher weight. Simpler structures make stronger predictions about their gaps [LEDGER: THM-NON-EMPIRICAL-SOLOMONOFF]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_impossible_element',
    description: 'An AI can "know" a fact about an unobserved object without training data, by computing the interpolation weight from the structural lattice. Positive, bounded, structure-dependent. Deterministic, obje [LEDGER: THM-IMPOSSIBLE-ELEMENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_prediction_without_observation',
    description: 'The structural hole has nonzero interpolation weight despite no direct observation. Weight comes entirely from neighbor structure. Formal content of non-empirical prediction [LEDGER: THM-PREDICTION-WITHOUT-OBSERVATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_inference_positive',
    description: 'Every token retains positive probability in void inference. The sliver prevents permanent exclusion from generation regardless of rejection history [LEDGER: THM-VOID-INFERENCE-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_inference_concentrates',
    description: 'The complement distribution sharpens with rejection accumulation. Tokens rejected more get lower weight. Generation gets more confident [LEDGER: THM-VOID-INFERENCE-CONCENTRATES]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_inference_coherent',
    description: 'Two void inference systems with the same rejection history produce the same output distribution. Deterministic given the void boundary [LEDGER: THM-VOID-INFERENCE-COHERENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_inference_subsumes_softmax',
    description: 'Void inference with single-step boundary equals standard softmax range. With multi-step accumulation, void inference is strictly richer (cross-step rejection memory) [LEDGER: THM-VOID-INFERENCE-SUBSUMES-SOFTMAX]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_inference_normalizable',
    description: 'Total weight across all tokens is positive, so the complement distribution can be normalized to a probability distribution [LEDGER: THM-VOID-INFERENCE-NORMALIZABLE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_retrocausal_consistent',
    description: 'Only trajectories consistent with the terminal state survive. Terminal constraints are satisfiable (every terminal weight is positive) [LEDGER: THM-RETROCAUSAL-CONSISTENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_retrocausal_positive',
    description: 'No valid trajectory is excluded. The sliver prevents false negatives in the pruning step. Weight >= 1 and weight != 0 [LEDGER: THM-RETROCAUSAL-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_retrocausal_sharpens',
    description: 'As generation progresses, the set of consistent continuations shrinks. Fewer tokens remain with low rejection counts [LEDGER: THM-RETROCAUSAL-SHARPENS]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_retrocausal_composable',
    description: 'Two retrocausal constraints compose. Intersection of consistent trajectories is nonempty because the sliver ensures weight >= 1 for every token under every constraint [LEDGER: THM-RETROCAUSAL-COMPOSABLE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_retrocausal_no_self_reference',
    description: 'Self-referential terminal constraints cannot annihilate any trajectory. The grandfather paradox applied to decoding [LEDGER: THM-RETROCAUSAL-NO-SELF-REFERENCE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_skip_preserves_topology',
    description: 'Skipping a zero-deficit layer preserves the total beta1 of the network. A layer with beta1 = 0 contributes nothing topologically [LEDGER: THM-TOPO-SKIP-PRESERVES-TOPOLOGY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_speedup_exact',
    description: 'Speedup from skipping a layer is deficit + 1. For zero-deficit layer, speedup = 1 [LEDGER: THM-TOPO-SPEEDUP-EXACT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_skip_composable',
    description: 'Multiple layer skips compose. Skipping layers with deficits d1 and d2 gives total speedup d1 + d2 + 2. Deficits are additive [LEDGER: THM-TOPO-SKIP-COMPOSABLE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_skip_bounded',
    description: 'Maximum number of skippable layers is bounded by the network depth [LEDGER: THM-TOPO-SKIP-BOUNDED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_minimum_compute',
    description: 'At least one layer must execute (the sliver applied to compute). Network with L layers can skip at most L - 1 [LEDGER: THM-TOPO-MINIMUM-COMPUTE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_topo_deficit_nonneg',
    description: 'Beta1 deficit is always non-negative. No layer has negative topological complexity [LEDGER: THM-TOPO-DEFICIT-NONNEG]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_deficit_exact',
    description: 'Semiotic deficit of a k-agent ensemble is exactly k - 1. Unavoidable information loss from folding multiple candidates to one winner [LEDGER: THM-ENSEMBLE-DEFICIT-EXACT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_deficit_positive',
    description: 'For any nontrivial ensemble (k >= 2), the deficit is positive. Folding always loses information. Free consensus is impossible [LEDGER: THM-ENSEMBLE-DEFICIT-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_dominates_single',
    description: 'Ensemble output (least-rejected candidate) has weight at least as high as any single agent. Complement voting is non-degrading [LEDGER: THM-ENSEMBLE-DOMINATES-SINGLE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_complement_voting',
    description: 'Every candidate retains positive weight in the complement vote. No agents output is ever completely eliminated [LEDGER: THM-ENSEMBLE-COMPLEMENT-VOTING]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_coherent',
    description: 'Two independent juries using the same rejection data select the same winner. Complement voting is objective [LEDGER: THM-ENSEMBLE-COHERENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_ensemble_scaling',
    description: 'Adding one more agent increases the deficit by exactly 1. Constant marginal information cost [LEDGER: THM-ENSEMBLE-SCALING]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_positive',
    description: 'Predicted completion has positive weight. The structural hole exists in the Buleyean sense [LEDGER: THM-NEI-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_dominates_guess',
    description: 'Structural prediction strictly dominates random guessing when neighbors provide nontrivial rejection data [LEDGER: THM-NEI-DOMINATES-GUESS]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_coherent',
    description: 'Two systems with the same lattice structure produce the same prediction. Non-empirical inference is objective [LEDGER: THM-NEI-COHERENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_bounded',
    description: 'Prediction weight bounded between 1 and rounds + 1. Always finite, always within Buleyean weight range [LEDGER: THM-NEI-BOUNDED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_mendeleev',
    description: 'Non-empirical inference is isomorphic to Mendeleevs periodic table prediction method. Both compute complement weight from neighbor-averaged void boundary [LEDGER: THM-NEI-MENDELEEV]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nei_structure_dominates',
    description: 'More neighbor rejection data produces sharper (lower) prediction weight. More structure = more constraint [LEDGER: THM-NEI-STRUCTURE-DOMINATES]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_novel_inference_forms_master',
    description: 'Complete composition: all five forms are well-defined and compose from the same Buleyean axioms. Void inference positive, retrocausal decoding satisfiable, topological skipping non-negative, ensemble  [LEDGER: THM-NOVEL-INFERENCE-FORMS-MASTER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_misfolding_zero_deficit',
    description: 'Correct protein folding reaches beta1 = 0 (native state). Zero misfolding deficit [LEDGER: THM-MISFOLDING-ZERO-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_misfolding_positive_deficit',
    description: 'Misfolded proteins have positive deficit (trapped in non-native state with unresolved cycles) [LEDGER: THM-MISFOLDING-POSITIVE-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_misfolding_deficit_bounded',
    description: 'Misfolding deficit is bounded by conformational complexity (conformations - 1) [LEDGER: THM-MISFOLDING-DEFICIT-BOUNDED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_language_convergence_min',
    description: 'Language acquisition requires at least spaceSize - 1 convergence rounds. Void walking over the phoneme space [LEDGER: THM-LANGUAGE-CONVERGENCE-MIN]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_larger_language_slower',
    description: 'Larger phoneme inventories require more convergence rounds. Hawaiian < English < Mandarin < !Xoo [LEDGER: THM-LARGER-LANGUAGE-SLOWER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_babbling_uniform',
    description: 'Pre-convergence babbling phase is uniform distribution (all-zero void boundary, all weights equal) [LEDGER: THM-BABBLING-UNIFORM]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_immune_never_zero',
    description: 'No pathogens threat weight ever reaches zero. The immune sliver: even maximally encountered pathogens retain weight >= 1 [LEDGER: THM-IMMUNE-NEVER-ZERO]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_less_rejected_more_threatening',
    description: 'Pathogens with fewer failed antibody bindings (less rejected) have higher threat weight. Novel pathogens most dangerous [LEDGER: THM-LESS-REJECTED-MORE-THREATENING]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_novel_pathogen_max_threat',
    description: 'Never-encountered pathogen has maximum threat weight = rounds + 1 (max uncertainty) [LEDGER: THM-NOVEL-PATHOGEN-MAX-THREAT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_pruning_deficit_exact',
    description: 'Neural pruning deficit = sqrtParams - 1. Over-pruning creates classical deficit [LEDGER: THM-PRUNING-DEFICIT-EXACT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_pruning_speedup',
    description: 'Optimal neural pruning speedup = deficit + 1 = sqrtParams. Composes quantum_speedup_equals_classical_deficit_plus_one [LEDGER: THM-PRUNING-SPEEDUP]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_full_multiplexing_liquidity',
    description: 'Full trading path multiplexing = zero liquidity deficit = maximum market liquidity [LEDGER: THM-FULL-MULTIPLEXING-LIQUIDITY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_serialized_market_deficit',
    description: 'Single-path market has maximum deficit = tradingPaths - 1 = maximum illiquidity [LEDGER: THM-SERIALIZED-MARKET-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_deficit_monotone_realization',
    description: 'Adding a trading venue reduces liquidity deficit. Deficit is monotone in realized paths [LEDGER: THM-DEFICIT-MONOTONE-REALIZATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_novel_predictions_master',
    description: 'All five predictions formally grounded: misfolding deficit bounded, language convergence positive, immune memory positive, pruning speedup = deficit + 1, full multiplexing = zero deficit [LEDGER: THM-NOVEL-PREDICTIONS-MASTER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_memory_never_forgotten',
    description: 'Memory strength is always positive (the sliver): no memory is ever fully forgotten regardless of failed retrieval count [LEDGER: THM-MEMORY-NEVER-FORGOTTEN]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_more_failures_weaker',
    description: 'More failed retrievals produce weaker memory. The forgetting curve is monotone in void count [LEDGER: THM-MORE-FAILURES-WEAKER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_perfect_retrieval_max',
    description: 'Perfect retrieval (zero failures) gives maximum strength = opportunities + 1 [LEDGER: THM-PERFECT-RETRIEVAL-MAX]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_climax_zero_deficit',
    description: 'Ecological climax community has zero succession deficit [LEDGER: THM-CLIMAX-ZERO-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_succession_monotone',
    description: 'Closer to climax means less succession deficit (monotone toward equilibrium) [LEDGER: THM-SUCCESSION-MONOTONE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_single_source_max_fragility',
    description: 'Single-source supply chain has maximum fragility deficit = potential - 1 [LEDGER: THM-SINGLE-SOURCE-MAX-FRAGILITY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_full_diversification_zero',
    description: 'Full supplier diversification eliminates fragility deficit [LEDGER: THM-FULL-DIVERSIFICATION-ZERO]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_more_suppliers_less_fragility',
    description: 'More active suppliers monotonically reduces fragility deficit [LEDGER: THM-MORE-SUPPLIERS-LESS-FRAGILITY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_deliberation_deficit_positive',
    description: 'Jury deliberation deficit is always positive for k >= 2 jurors. Free consensus is impossible [LEDGER: THM-DELIBERATION-DEFICIT-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_unanimous_zero_gap',
    description: 'Unanimous verdict (votes >= threshold) has zero agreement gap [LEDGER: THM-UNANIMOUS-ZERO-GAP]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_larger_jury_larger_deficit',
    description: 'Larger jury has larger deliberation deficit (more information lost in fold) [LEDGER: THM-LARGER-JURY-LARGER-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_perfect_transfer_zero',
    description: 'Perfect skill transfer (all skills applicable) has zero transfer deficit [LEDGER: THM-PERFECT-TRANSFER-ZERO]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_more_transferable_less_deficit',
    description: 'More transferable skills monotonically reduces transfer deficit [LEDGER: THM-MORE-TRANSFERABLE-LESS-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_no_transfer_max_deficit',
    description: 'Zero transferable skills gives maximum transfer deficit = source skills [LEDGER: THM-NO-TRANSFER-MAX-DEFICIT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_predictions_round8_master',
    description: 'All five predictions compose: memory positive, climax zero deficit, full diversification zero fragility, deliberation positive, perfect transfer zero deficit [LEDGER: THM-PREDICTIONS-ROUND8-MASTER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_convergence_schema',
    description: 'Conditional (7 physics axioms) [LEDGER: THM-CONVERGENCE-SCHEMA]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_completeness_dag',
    description: 'Partially constructive [LEDGER: THM-COMPLETENESS-DAG]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_queue_containment',
    description: 'Superseded by THM-QUEUE-SUBSUMPTION [LEDGER: THM-QUEUE-CONTAINMENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_queue_subsumption',
    description: 'Executable (bidirectional) [LEDGER: THM-QUEUE-SUBSUMPTION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_queue_limit_schema',
    description: 'Conditional (standard measure-theoretic regularity) [LEDGER: THM-QUEUE-LIMIT-SCHEMA]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_queue_state_dependent_schema',
    description: 'Mostly constructive (7/10 discharged) [LEDGER: THM-QUEUE-STATE-DEPENDENT-SCHEMA]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_queue_adaptive_supremum',
    description: 'Constructive synthesis [LEDGER: THM-QUEUE-ADAPTIVE-SUPREMUM]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rg_fixed_points',
    description: 'Iterated coarsening as renormalization group flow: cumulative heat is monotone along trajectories, information loss is additive (chain rule), RG fixed points have injective pushforward (singleton fibe [LEDGER: THM-RG-FIXED-POINTS]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_thermo_traced_monoidal',
    description: 'Traced monoidal semantics coupled to thermodynamics: trace = coarsening (projection away feedback component), non-trivial feedback generates strictly positive Landauer heat, iterated traces increase c [LEDGER: THM-THERMO-TRACED-MONOIDAL]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_fold_heat_hierarchy',
    description: 'Classification of folds by thermodynamic heat signature: injective = 0 heat, non-injective fibers generate strictly positive heat, uniform fold heat = kT ln2 × H(X [LEDGER: THM-FOLD-HEAT-HIERARCHY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_semiotic_peace',
    description: 'Formal theory of confusion, war, and hope: semiotic fold is a coarsening with Landauer heat (confusion generates heat), successive folds without context accumulate heat monotonically (war as cumulativ [LEDGER: THM-SEMIOTIC-PEACE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_attenuates_failure',
    description: 'Community CRDT context reduces the scheduling deficit of any failure topology. Each CRDT-synced observation (win counts, latency means, failure rates, disagreement records) acts as one unit of shared  [LEDGER: THM-COMMUNITY-ATTENUATES-FAILURE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_monotone_nondegradation',
    description: 'Community memory cannot increase the expected cost of an already-optimal backend. If the scheduling deficit is already non-positive (good hand), community context keeps it non-positive. Good hands sta [LEDGER: THM-COMMUNITY-MONOTONE-NONDEGRADATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_strict_domination',
    description: 'When community context is positive and the failure topology has positive deficit (bad hand), the community-reduced deficit is strictly less than the bare deficit. Combined with nondegradation: Pareto  [LEDGER: THM-COMMUNITY-STRICT-DOMINATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_bridges_tares',
    description: 'Community context reduces unbridged tares (failure modes not covered). More community knowledge means fewer uncovered failure modes. Sufficient context bridges all tares. [LEDGER: THM-COMMUNITY-BRIDGES-TARES]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_bule_convergence',
    description: 'The Bule deficit (scheduling gap in Bule units) decreases monotonically with community context. Each CRDT sync round reduces the deficit by exactly one Bule when there is remaining deficit. Sufficient [LEDGER: THM-COMMUNITY-BULE-CONVERGENCE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_dominance_theory',
    description: 'Master theorem: for any failure topology with decisionStreams < failurePaths and positive community context: (1) failure deficit is real, (2) community attenuates failure strictly, (3) Bule deficit mo [LEDGER: THM-COMMUNITY-DOMINANCE-THEORY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_dominance_model',
    description: 'Model-checked community fabric: safety (Bule bounded, non-negative, monotone, adaptive dominates static, nondegradation stable), liveness (eventually converges, eventually zero deficit), domination (p [LEDGER: THM-COMMUNITY-DOMINANCE-MODEL]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_community_is_skyrms_walker',
    description: 'The community CRDT plays the role of Skyrms Walker S. The scheduling deficit IS the negotiation deficit. Community attenuation IS Skyrms mediation. One CRDT sync round = one mediation round = one Bule [LEDGER: THM-COMMUNITY-IS-SKYRMS-WALKER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_bule_zero_is_nadir',
    description: 'The Skyrms nadir (inter-walker distance = 0) is exactly the state where buleDeficit = 0. Biconditional: buleDeficit = 0 iff interWalkerDistance = 0. At the nadirContext, Bule = 0. Below nadirContext,  [LEDGER: THM-BULE-ZERO-IS-NADIR]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_nadir_algebraic',
    description: 'The nadir can be computed algebraically: nadirContext = walkerA_dims + walkerB_dims - 1. At that context Bule = 0. Below that context Bule > 0. The solution is closed-form. No void walking needed. Set [LEDGER: THM-NADIR-ALGEBRAIC]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_skyrms_nadir_is_bule_zero',
    description: 'Master theorem: three equivalent characterizations of the Skyrms nadir. (I) Community IS the mediator: deficit identification + attenuation = mediation. (II) Bule=0 IS the nadir: convergence at nadirC [LEDGER: THM-SKYRMS-NADIR-IS-BULE-ZERO]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_skyrms_nadir_bule_model',
    description: 'Model-checked equivalence of three-walker convergence and Bule convergence: Bule nonneg, bounded, nadir constant, community tracks rounds, attenuation = convergence, algebraic nadir correct, solve-don [LEDGER: THM-SKYRMS-NADIR-BULE-MODEL]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_diversity_optimality',
    description: 'Composition theorem: diversity is the monotonically optimal, thermodynamically necessary condition for information-preserving computation in fork/race/fold systems. Five pillars: (1) Monotonicity — ad [LEDGER: THM-DIVERSITY-OPTIMALITY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rejection_gradient',
    description: 'Rejection-driven policy gradient is well-defined: all weights > 0 [LEDGER: THM-REJECTION-GRADIENT]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rejection_data_advantage',
    description: 'Rejection provides (N-1)x more data than reward [LEDGER: THM-REJECTION-DATA-ADVANTAGE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rejection_exploration',
    description: 'Rejection RL preserves exploration (sliver) [LEDGER: THM-REJECTION-EXPLORATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_rejection_concentration',
    description: 'Gradient concentrates on least-rejected actions [LEDGER: THM-REJECTION-CONCENTRATION]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_beta1_compute_monotone',
    description: 'Higher beta-1 -> more compute allocated [LEDGER: THM-BETA1-COMPUTE-MONOTONE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_minimum_compute',
    description: 'Every token gets >= 1 layer [LEDGER: THM-MINIMUM-COMPUTE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_total_compute_bounded',
    description: 'Total compute bounded by N x (maxBeta1 + 1) [LEDGER: THM-TOTAL-COMPUTE-BOUNDED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_certain_token_minimal',
    description: 'Zero-beta-1 token gets exactly 1 layer [LEDGER: THM-CERTAIN-TOKEN-MINIMAL]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_cache_smaller',
    description: 'Void cache <= full KV cache when d_model >= 2 [LEDGER: THM-VOID-CACHE-SMALLER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_cache_reconstructs',
    description: 'Same rejection counts -> same complement weights [LEDGER: THM-VOID-CACHE-RECONSTRUCTS]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_cache_update',
    description: 'Adding one rejection is O(1) [LEDGER: THM-VOID-CACHE-UPDATE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_void_cache_positive',
    description: 'All dimensions retain positive weight [LEDGER: THM-VOID-CACHE-POSITIVE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_free_energy_decreasing',
    description: 'Computing one layer reduces free energy by 1 [LEDGER: THM-FREE-ENERGY-DECREASING]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_exit_eventually_reached',
    description: 'Free energy reaches zero at totalLayers [LEDGER: THM-EXIT-EVENTUALLY-REACHED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_exit_saves_energy',
    description: 'Remaining = totalLayers - layersComputed [LEDGER: THM-EXIT-SAVES-ENERGY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_exit_deterministic',
    description: 'Same model + same layers computed = same exit [LEDGER: THM-EXIT-DETERMINISTIC]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_inverse_well_defined',
    description: 'Inverse distribution valid (all positive, total positive) [LEDGER: THM-INVERSE-WELL-DEFINED]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_inverse_favors_simple',
    description: 'Least-rejected hypothesis has highest weight [LEDGER: THM-INVERSE-FAVORS-SIMPLE]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_inverse_positivity',
    description: 'No hypothesis reaches zero probability [LEDGER: THM-INVERSE-POSITIVITY]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  },
  {
    name: 'thm_novel_inference_master',
    description: 'All five mechanisms compose from three axioms + coherence [LEDGER: THM-NOVEL-INFERENCE-MASTER]',
    inputSchema: { type: 'object', properties: { query: { type: 'string' } } },
  }
];

export const LEDGER_HANDLER_CASES: Record<string, { theorem: string; claim: string; mechanization: string; section: string }> = {
  'thm_hole_positive_weight': { theorem: 'THM-HOLE-POSITIVE-WEIGHT', claim: 'A structural hole always has strictly positive interpolation weight. The complement distribution never assigns zero probability to any hole. Never say never in prediction', mechanization: 'Lean theorem `hole_has_positive_weight` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_interpolation_bounded': { theorem: 'THM-INTERPOLATION-BOUNDED', claim: 'The interpolation weight is bounded between 1 and rounds + 1. The prediction is always finite and within the Buleyean weight range', mechanization: 'Lean theorem `interpolation_weight_bounded` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_rejection_reduces_prediction': { theorem: 'THM-REJECTION-REDUCES-PREDICTION', claim: 'More neighbor rejection = lower prediction weight. Structure constrains: neighbors rejection data shapes the holes complement distribution', mechanization: 'Lean theorem `rejection_reduces_prediction` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_lattice_partition': { theorem: 'THM-LATTICE-PARTITION', claim: 'The lattice is exactly partitioned into observed positions and holes. observedCount + holeCount = totalPositions. Conservation law of the structural lattice', mechanization: 'Lean theorem `lattice_partition` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_neighbor_dominates_uninformed': { theorem: 'THM-NEIGHBOR-DOMINATES-UNINFORMED', claim: 'Structural prediction with neighbor data is at least as informative as uninformed guessing. Interpolation weight <= uninformed weight. Structure provides signal', mechanization: 'Lean theorem `neighbor_dominates_uninformed` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_strict_dominance': { theorem: 'THM-STRICT-DOMINANCE', claim: 'With nontrivial neighbor rejection (neighborVoidSum > 0), structural prediction is strictly more informative than guessing. The gap equals min(voidSum, roundsSum)', mechanization: 'Lean theorem `strict_dominance_with_rejection` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_holes_ordered': { theorem: 'THM-HOLES-ORDERED', claim: 'Two holes with different neighbor rejection receive different predictions. The lattice differentiates. Formalizes: "gallium is more like aluminum than iron"', mechanization: 'Lean theorem `holes_ordered` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_mendeleev_is_complement': { theorem: 'THM-MENDELEEV-IS-COMPLEMENT', claim: 'Mendeleevs interpolation method is isomorphic to computing the Buleyean complement weight from neighbor-aggregated void boundary. Same formula: rounds - min(void, rounds) + 1', mechanization: 'Lean theorem `mendeleev_is_complement` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_algebraic_hole_is_void_gap': { theorem: 'THM-ALGEBRAIC-HOLE-IS-VOID-GAP', claim: 'Algebraic holes (Diracs positron, Paulis neutrino) are positions demanded by lattice partition conservation. The lattice forces the hole to exist; the complement distribution predicts its properties', mechanization: 'Lean theorem `algebraic_hole_is_void_gap` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_non_empirical_solomonoff': { theorem: 'THM-NON-EMPIRICAL-SOLOMONOFF', claim: 'Non-empirical prediction composes with Solomonoff prediction. Holes in simpler lattices get higher weight. Simpler structures make stronger predictions about their gaps', mechanization: 'Lean theorem `non_empirical_solomonoff_compose` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_impossible_element': { theorem: 'THM-IMPOSSIBLE-ELEMENT', claim: 'An AI can "know" a fact about an unobserved object without training data, by computing the interpolation weight from the structural lattice. Positive, bounded, structure-dependent. Deterministic, obje', mechanization: 'Lean theorem `impossible_element` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_prediction_without_observation': { theorem: 'THM-PREDICTION-WITHOUT-OBSERVATION', claim: 'The structural hole has nonzero interpolation weight despite no direct observation. Weight comes entirely from neighbor structure. Formal content of non-empirical prediction', mechanization: 'Lean theorem `prediction_without_observation` in `NonEmpiricalPrediction.lean`', section: 'Non-Empirical Prediction (§15.22)' },
  'thm_void_inference_positive': { theorem: 'THM-VOID-INFERENCE-POSITIVE', claim: 'Every token retains positive probability in void inference. The sliver prevents permanent exclusion from generation regardless of rejection history', mechanization: 'Lean theorem `void_inference_positive` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_void_inference_concentrates': { theorem: 'THM-VOID-INFERENCE-CONCENTRATES', claim: 'The complement distribution sharpens with rejection accumulation. Tokens rejected more get lower weight. Generation gets more confident', mechanization: 'Lean theorem `void_inference_concentrates` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_void_inference_coherent': { theorem: 'THM-VOID-INFERENCE-COHERENT', claim: 'Two void inference systems with the same rejection history produce the same output distribution. Deterministic given the void boundary', mechanization: 'Lean theorem `void_inference_coherent` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_void_inference_subsumes_softmax': { theorem: 'THM-VOID-INFERENCE-SUBSUMES-SOFTMAX', claim: 'Void inference with single-step boundary equals standard softmax range. With multi-step accumulation, void inference is strictly richer (cross-step rejection memory)', mechanization: 'Lean theorem `void_inference_subsumes_softmax` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_void_inference_normalizable': { theorem: 'THM-VOID-INFERENCE-NORMALIZABLE', claim: 'Total weight across all tokens is positive, so the complement distribution can be normalized to a probability distribution', mechanization: 'Lean theorem `void_inference_normalizable` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_retrocausal_consistent': { theorem: 'THM-RETROCAUSAL-CONSISTENT', claim: 'Only trajectories consistent with the terminal state survive. Terminal constraints are satisfiable (every terminal weight is positive)', mechanization: 'Lean theorem `retrocausal_consistent` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_retrocausal_positive': { theorem: 'THM-RETROCAUSAL-POSITIVE', claim: 'No valid trajectory is excluded. The sliver prevents false negatives in the pruning step. Weight >= 1 and weight != 0', mechanization: 'Lean theorem `retrocausal_positive` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_retrocausal_sharpens': { theorem: 'THM-RETROCAUSAL-SHARPENS', claim: 'As generation progresses, the set of consistent continuations shrinks. Fewer tokens remain with low rejection counts', mechanization: 'Lean theorem `retrocausal_sharpens` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_retrocausal_composable': { theorem: 'THM-RETROCAUSAL-COMPOSABLE', claim: 'Two retrocausal constraints compose. Intersection of consistent trajectories is nonempty because the sliver ensures weight >= 1 for every token under every constraint', mechanization: 'Lean theorem `retrocausal_composable` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_retrocausal_no_self_reference': { theorem: 'THM-RETROCAUSAL-NO-SELF-REFERENCE', claim: 'Self-referential terminal constraints cannot annihilate any trajectory. The grandfather paradox applied to decoding', mechanization: 'Lean theorem `retrocausal_no_self_reference` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_skip_preserves_topology': { theorem: 'THM-TOPO-SKIP-PRESERVES-TOPOLOGY', claim: 'Skipping a zero-deficit layer preserves the total beta1 of the network. A layer with beta1 = 0 contributes nothing topologically', mechanization: 'Lean theorem `topo_skip_preserves_topology` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_speedup_exact': { theorem: 'THM-TOPO-SPEEDUP-EXACT', claim: 'Speedup from skipping a layer is deficit + 1. For zero-deficit layer, speedup = 1', mechanization: 'Lean theorem `topo_speedup_exact` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_skip_composable': { theorem: 'THM-TOPO-SKIP-COMPOSABLE', claim: 'Multiple layer skips compose. Skipping layers with deficits d1 and d2 gives total speedup d1 + d2 + 2. Deficits are additive', mechanization: 'Lean theorem `topo_skip_composable` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_skip_bounded': { theorem: 'THM-TOPO-SKIP-BOUNDED', claim: 'Maximum number of skippable layers is bounded by the network depth', mechanization: 'Lean theorem `topo_skip_bounded` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_minimum_compute': { theorem: 'THM-TOPO-MINIMUM-COMPUTE', claim: 'At least one layer must execute (the sliver applied to compute). Network with L layers can skip at most L - 1', mechanization: 'Lean theorem `topo_minimum_compute` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_topo_deficit_nonneg': { theorem: 'THM-TOPO-DEFICIT-NONNEG', claim: 'Beta1 deficit is always non-negative. No layer has negative topological complexity', mechanization: 'Lean theorem `topo_deficit_nonneg` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_deficit_exact': { theorem: 'THM-ENSEMBLE-DEFICIT-EXACT', claim: 'Semiotic deficit of a k-agent ensemble is exactly k - 1. Unavoidable information loss from folding multiple candidates to one winner', mechanization: 'Lean theorem `ensemble_deficit_exact` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_deficit_positive': { theorem: 'THM-ENSEMBLE-DEFICIT-POSITIVE', claim: 'For any nontrivial ensemble (k >= 2), the deficit is positive. Folding always loses information. Free consensus is impossible', mechanization: 'Lean theorem `ensemble_deficit_positive` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_dominates_single': { theorem: 'THM-ENSEMBLE-DOMINATES-SINGLE', claim: 'Ensemble output (least-rejected candidate) has weight at least as high as any single agent. Complement voting is non-degrading', mechanization: 'Lean theorem `ensemble_dominates_single` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_complement_voting': { theorem: 'THM-ENSEMBLE-COMPLEMENT-VOTING', claim: 'Every candidate retains positive weight in the complement vote. No agents output is ever completely eliminated', mechanization: 'Lean theorem `ensemble_complement_voting` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_coherent': { theorem: 'THM-ENSEMBLE-COHERENT', claim: 'Two independent juries using the same rejection data select the same winner. Complement voting is objective', mechanization: 'Lean theorem `ensemble_coherent` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_ensemble_scaling': { theorem: 'THM-ENSEMBLE-SCALING', claim: 'Adding one more agent increases the deficit by exactly 1. Constant marginal information cost', mechanization: 'Lean theorem `ensemble_scaling` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_positive': { theorem: 'THM-NEI-POSITIVE', claim: 'Predicted completion has positive weight. The structural hole exists in the Buleyean sense', mechanization: 'Lean theorem `nei_positive` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_dominates_guess': { theorem: 'THM-NEI-DOMINATES-GUESS', claim: 'Structural prediction strictly dominates random guessing when neighbors provide nontrivial rejection data', mechanization: 'Lean theorem `nei_dominates_guess` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_coherent': { theorem: 'THM-NEI-COHERENT', claim: 'Two systems with the same lattice structure produce the same prediction. Non-empirical inference is objective', mechanization: 'Lean theorem `nei_coherent` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_bounded': { theorem: 'THM-NEI-BOUNDED', claim: 'Prediction weight bounded between 1 and rounds + 1. Always finite, always within Buleyean weight range', mechanization: 'Lean theorem `nei_bounded` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_mendeleev': { theorem: 'THM-NEI-MENDELEEV', claim: 'Non-empirical inference is isomorphic to Mendeleevs periodic table prediction method. Both compute complement weight from neighbor-averaged void boundary', mechanization: 'Lean theorem `nei_mendeleev` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_nei_structure_dominates': { theorem: 'THM-NEI-STRUCTURE-DOMINATES', claim: 'More neighbor rejection data produces sharper (lower) prediction weight. More structure = more constraint', mechanization: 'Lean theorem `nei_structure_dominates` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_novel_inference_forms_master': { theorem: 'THM-NOVEL-INFERENCE-FORMS-MASTER', claim: 'Complete composition: all five forms are well-defined and compose from the same Buleyean axioms. Void inference positive, retrocausal decoding satisfiable, topological skipping non-negative, ensemble ', mechanization: 'TLA+ `NovelInferenceForms.tla` (11 invariants) + Lean theorem `novel_inference_forms_master` in `NovelInferenceForms.lean`', section: 'Five Novel AI Inference Forms (§15.24)' },
  'thm_misfolding_zero_deficit': { theorem: 'THM-MISFOLDING-ZERO-DEFICIT', claim: 'Correct protein folding reaches beta1 = 0 (native state). Zero misfolding deficit', mechanization: 'Lean theorem `correct_folding_zero_deficit` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_misfolding_positive_deficit': { theorem: 'THM-MISFOLDING-POSITIVE-DEFICIT', claim: 'Misfolded proteins have positive deficit (trapped in non-native state with unresolved cycles)', mechanization: 'Lean theorem `misfolding_positive_deficit` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_misfolding_deficit_bounded': { theorem: 'THM-MISFOLDING-DEFICIT-BOUNDED', claim: 'Misfolding deficit is bounded by conformational complexity (conformations - 1)', mechanization: 'Lean theorem `misfolding_deficit_bounded` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_language_convergence_min': { theorem: 'THM-LANGUAGE-CONVERGENCE-MIN', claim: 'Language acquisition requires at least spaceSize - 1 convergence rounds. Void walking over the phoneme space', mechanization: 'Lean theorem `language_convergence_minimum` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_larger_language_slower': { theorem: 'THM-LARGER-LANGUAGE-SLOWER', claim: 'Larger phoneme inventories require more convergence rounds. Hawaiian < English < Mandarin < !Xoo', mechanization: 'Lean theorem `larger_language_slower` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_babbling_uniform': { theorem: 'THM-BABBLING-UNIFORM', claim: 'Pre-convergence babbling phase is uniform distribution (all-zero void boundary, all weights equal)', mechanization: 'Lean theorem `babbling_is_uniform` in `NovelPredictions.lean`, delegating to `fold_without_evidence_is_coinflip`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_immune_never_zero': { theorem: 'THM-IMMUNE-NEVER-ZERO', claim: 'No pathogens threat weight ever reaches zero. The immune sliver: even maximally encountered pathogens retain weight >= 1', mechanization: 'Lean theorem `immune_never_zero_threat` in `NovelPredictions.lean`, delegating to `buleyean_positivity`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_less_rejected_more_threatening': { theorem: 'THM-LESS-REJECTED-MORE-THREATENING', claim: 'Pathogens with fewer failed antibody bindings (less rejected) have higher threat weight. Novel pathogens most dangerous', mechanization: 'Lean theorem `less_rejected_more_threatening` in `NovelPredictions.lean`, delegating to `buleyean_concentration`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_novel_pathogen_max_threat': { theorem: 'THM-NOVEL-PATHOGEN-MAX-THREAT', claim: 'Never-encountered pathogen has maximum threat weight = rounds + 1 (max uncertainty)', mechanization: 'Lean theorem `novel_pathogen_max_threat` in `NovelPredictions.lean`, delegating to `buleyean_max_uncertainty`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_pruning_deficit_exact': { theorem: 'THM-PRUNING-DEFICIT-EXACT', claim: 'Neural pruning deficit = sqrtParams - 1. Over-pruning creates classical deficit', mechanization: 'Lean theorem `pruning_deficit_exact` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_pruning_speedup': { theorem: 'THM-PRUNING-SPEEDUP', claim: 'Optimal neural pruning speedup = deficit + 1 = sqrtParams. Composes quantum_speedup_equals_classical_deficit_plus_one', mechanization: 'Lean theorem `pruning_speedup_equals_deficit_plus_one` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_full_multiplexing_liquidity': { theorem: 'THM-FULL-MULTIPLEXING-LIQUIDITY', claim: 'Full trading path multiplexing = zero liquidity deficit = maximum market liquidity', mechanization: 'Lean theorem `full_multiplexing_max_liquidity` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_serialized_market_deficit': { theorem: 'THM-SERIALIZED-MARKET-DEFICIT', claim: 'Single-path market has maximum deficit = tradingPaths - 1 = maximum illiquidity', mechanization: 'Lean theorem `serialized_market_max_deficit` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_deficit_monotone_realization': { theorem: 'THM-DEFICIT-MONOTONE-REALIZATION', claim: 'Adding a trading venue reduces liquidity deficit. Deficit is monotone in realized paths', mechanization: 'Lean theorem `deficit_monotone_in_realization` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_novel_predictions_master': { theorem: 'THM-NOVEL-PREDICTIONS-MASTER', claim: 'All five predictions formally grounded: misfolding deficit bounded, language convergence positive, immune memory positive, pruning speedup = deficit + 1, full multiplexing = zero deficit', mechanization: 'Lean theorem `novel_predictions_master` in `NovelPredictions.lean`', section: 'Novel Cross-Domain Predictions (§19.11)' },
  'thm_memory_never_forgotten': { theorem: 'THM-MEMORY-NEVER-FORGOTTEN', claim: 'Memory strength is always positive (the sliver): no memory is ever fully forgotten regardless of failed retrieval count', mechanization: 'Lean theorem `memory_never_fully_forgotten` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_more_failures_weaker': { theorem: 'THM-MORE-FAILURES-WEAKER', claim: 'More failed retrievals produce weaker memory. The forgetting curve is monotone in void count', mechanization: 'Lean theorem `more_failures_weaker_memory` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_perfect_retrieval_max': { theorem: 'THM-PERFECT-RETRIEVAL-MAX', claim: 'Perfect retrieval (zero failures) gives maximum strength = opportunities + 1', mechanization: 'Lean theorem `perfect_retrieval_max_strength` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_climax_zero_deficit': { theorem: 'THM-CLIMAX-ZERO-DEFICIT', claim: 'Ecological climax community has zero succession deficit', mechanization: 'Lean theorem `climax_zero_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_succession_monotone': { theorem: 'THM-SUCCESSION-MONOTONE', claim: 'Closer to climax means less succession deficit (monotone toward equilibrium)', mechanization: 'Lean theorem `closer_to_climax_less_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_single_source_max_fragility': { theorem: 'THM-SINGLE-SOURCE-MAX-FRAGILITY', claim: 'Single-source supply chain has maximum fragility deficit = potential - 1', mechanization: 'Lean theorem `single_source_max_fragility` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_full_diversification_zero': { theorem: 'THM-FULL-DIVERSIFICATION-ZERO', claim: 'Full supplier diversification eliminates fragility deficit', mechanization: 'Lean theorem `full_diversification_zero_fragility` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_more_suppliers_less_fragility': { theorem: 'THM-MORE-SUPPLIERS-LESS-FRAGILITY', claim: 'More active suppliers monotonically reduces fragility deficit', mechanization: 'Lean theorem `more_suppliers_less_fragility` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_deliberation_deficit_positive': { theorem: 'THM-DELIBERATION-DEFICIT-POSITIVE', claim: 'Jury deliberation deficit is always positive for k >= 2 jurors. Free consensus is impossible', mechanization: 'Lean theorem `deliberation_deficit_positive` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_unanimous_zero_gap': { theorem: 'THM-UNANIMOUS-ZERO-GAP', claim: 'Unanimous verdict (votes >= threshold) has zero agreement gap', mechanization: 'Lean theorem `unanimous_verdict_zero_gap` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_larger_jury_larger_deficit': { theorem: 'THM-LARGER-JURY-LARGER-DEFICIT', claim: 'Larger jury has larger deliberation deficit (more information lost in fold)', mechanization: 'Lean theorem `larger_jury_larger_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_perfect_transfer_zero': { theorem: 'THM-PERFECT-TRANSFER-ZERO', claim: 'Perfect skill transfer (all skills applicable) has zero transfer deficit', mechanization: 'Lean theorem `perfect_transfer_zero_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_more_transferable_less_deficit': { theorem: 'THM-MORE-TRANSFERABLE-LESS-DEFICIT', claim: 'More transferable skills monotonically reduces transfer deficit', mechanization: 'Lean theorem `more_transferable_less_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_no_transfer_max_deficit': { theorem: 'THM-NO-TRANSFER-MAX-DEFICIT', claim: 'Zero transferable skills gives maximum transfer deficit = source skills', mechanization: 'Lean theorem `no_transfer_max_deficit` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_predictions_round8_master': { theorem: 'THM-PREDICTIONS-ROUND8-MASTER', claim: 'All five predictions compose: memory positive, climax zero deficit, full diversification zero fragility, deliberation positive, perfect transfer zero deficit', mechanization: 'TLA+ `PredictionsRound8.tla` (7 invariants) + Lean theorem `five_predictions_round8` in `PredictionsRound8.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_convergence_schema': { theorem: 'THM-CONVERGENCE-SCHEMA', claim: 'Conditional (7 physics axioms)', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_completeness_dag': { theorem: 'THM-COMPLETENESS-DAG', claim: 'Partially constructive', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_queue_containment': { theorem: 'THM-QUEUE-CONTAINMENT', claim: 'Superseded by THM-QUEUE-SUBSUMPTION', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_queue_subsumption': { theorem: 'THM-QUEUE-SUBSUMPTION', claim: 'Executable (bidirectional)', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_queue_limit_schema': { theorem: 'THM-QUEUE-LIMIT-SCHEMA', claim: 'Conditional (standard measure-theoretic regularity)', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_queue_state_dependent_schema': { theorem: 'THM-QUEUE-STATE-DEPENDENT-SCHEMA', claim: 'Mostly constructive (7/10 discharged)', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_queue_adaptive_supremum': { theorem: 'THM-QUEUE-ADAPTIVE-SUPREMUM', claim: 'Constructive synthesis', mechanization: '', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_rg_fixed_points': { theorem: 'THM-RG-FIXED-POINTS', claim: 'Iterated coarsening as renormalization group flow: cumulative heat is monotone along trajectories, information loss is additive (chain rule), RG fixed points have injective pushforward (singleton fibe', mechanization: 'Lean theorems `trajectory_information_loss_additive`, `trajectory_cumulative_heat_monotone`, `fixed_point_characterization`, `fixed_point_minimum_heat', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_thermo_traced_monoidal': { theorem: 'THM-THERMO-TRACED-MONOIDAL', claim: 'Traced monoidal semantics coupled to thermodynamics: trace = coarsening (projection away feedback component), non-trivial feedback generates strictly positive Landauer heat, iterated traces increase c', mechanization: 'Lean theorems `trace_heat_nonneg`, `trace_heat_pos_of_nontrivial_feedback`, `iterated_trace_heat_monotone`, `trace_vanishing_heat`, `trace_vanishing_l', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_fold_heat_hierarchy': { theorem: 'THM-FOLD-HEAT-HIERARCHY', claim: 'Classification of folds by thermodynamic heat signature: injective = 0 heat, non-injective fibers generate strictly positive heat, uniform fold heat = kT ln2 × H(X', mechanization: '`Fintype α`, `Fintype β`, `PMF α`, `DecidableEq β`; non-injective requires witness pair with positive mass; algorithm decomposition uses chain rule', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_semiotic_peace': { theorem: 'THM-SEMIOTIC-PEACE', claim: 'Formal theory of confusion, war, and hope: semiotic fold is a coarsening with Landauer heat (confusion generates heat), successive folds without context accumulate heat monotonically (war as cumulativ', mechanization: 'Lean theorems `confusion_irreducibility`, `confusion_generates_heat`, `confusion_heat_nonneg`, `war_as_cumulative_heat`, `war_three_stage_monotone`, `', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_attenuates_failure': { theorem: 'THM-COMMUNITY-ATTENUATES-FAILURE', claim: 'Community CRDT context reduces the scheduling deficit of any failure topology. Each CRDT-synced observation (win counts, latency means, failure rates, disagreement records) acts as one unit of shared ', mechanization: 'Lean theorem `community_attenuates_failure` in `CommunityDominance.lean` composing with `SemioticPeace.semiotic_context_reduces` via `failureToSemioti', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_monotone_nondegradation': { theorem: 'THM-COMMUNITY-MONOTONE-NONDEGRADATION', claim: 'Community memory cannot increase the expected cost of an already-optimal backend. If the scheduling deficit is already non-positive (good hand), community context keeps it non-positive. Good hands sta', mechanization: 'Lean theorem `community_monotone_nondegradation` in `CommunityDominance.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_strict_domination': { theorem: 'THM-COMMUNITY-STRICT-DOMINATION', claim: 'When community context is positive and the failure topology has positive deficit (bad hand), the community-reduced deficit is strictly less than the bare deficit. Combined with nondegradation: Pareto ', mechanization: 'Lean theorem `community_strict_domination` in `CommunityDominance.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_bridges_tares': { theorem: 'THM-COMMUNITY-BRIDGES-TARES', claim: 'Community context reduces unbridged tares (failure modes not covered). More community knowledge means fewer uncovered failure modes. Sufficient context bridges all tares.', mechanization: 'Lean theorems `community_bridges_tares`, `community_bridges_all_tares` in `CommunityDominance.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_bule_convergence': { theorem: 'THM-COMMUNITY-BULE-CONVERGENCE', claim: 'The Bule deficit (scheduling gap in Bule units) decreases monotonically with community context. Each CRDT sync round reduces the deficit by exactly one Bule when there is remaining deficit. Sufficient', mechanization: 'Lean theorems `bule_deficit_nonneg`, `bule_deficit_monotone_decreasing`, `bule_deficit_strict_progress`, `bule_convergence`, `bule_convergence_rate_bo', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_dominance_theory': { theorem: 'THM-COMMUNITY-DOMINANCE-THEORY', claim: 'Master theorem: for any failure topology with decisionStreams < failurePaths and positive community context: (1) failure deficit is real, (2) community attenuates failure strictly, (3) Bule deficit mo', mechanization: 'Lean theorem `community_dominance_theory` in `CommunityDominance.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_dominance_model': { theorem: 'THM-COMMUNITY-DOMINANCE-MODEL', claim: 'Model-checked community fabric: safety (Bule bounded, non-negative, monotone, adaptive dominates static, nondegradation stable), liveness (eventually converges, eventually zero deficit), domination (p', mechanization: 'TLA+ `CommunityDominance.tla` + `CommunityDominance.cfg` with 11 invariants and 6 temporal properties', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_community_is_skyrms_walker': { theorem: 'THM-COMMUNITY-IS-SKYRMS-WALKER', claim: 'The community CRDT plays the role of Skyrms Walker S. The scheduling deficit IS the negotiation deficit. Community attenuation IS Skyrms mediation. One CRDT sync round = one mediation round = one Bule', mechanization: 'Lean theorems `community_deficit_is_negotiation_deficit` and `community_attenuation_is_mediation` in `SkyrmsNadirBule.lean` composing with `Negotiatio', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_bule_zero_is_nadir': { theorem: 'THM-BULE-ZERO-IS-NADIR', claim: 'The Skyrms nadir (inter-walker distance = 0) is exactly the state where buleDeficit = 0. Biconditional: buleDeficit = 0 iff interWalkerDistance = 0. At the nadirContext, Bule = 0. Below nadirContext, ', mechanization: 'Lean theorems `bule_zero_at_nadir`, `bule_zero_implies_nadir`, `nadir_implies_bule_zero`, `bule_zero_iff_nadir` in `SkyrmsNadirBule.lean`', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_nadir_algebraic': { theorem: 'THM-NADIR-ALGEBRAIC', claim: 'The nadir can be computed algebraically: nadirContext = walkerA_dims + walkerB_dims - 1. At that context Bule = 0. Below that context Bule > 0. The solution is closed-form. No void walking needed. Set', mechanization: 'Lean theorem `nadir_algebraic` in `SkyrmsNadirBule.lean` (four-part conjunction: value, convergence, minimality, positivity)', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_skyrms_nadir_is_bule_zero': { theorem: 'THM-SKYRMS-NADIR-IS-BULE-ZERO', claim: 'Master theorem: three equivalent characterizations of the Skyrms nadir. (I) Community IS the mediator: deficit identification + attenuation = mediation. (II) Bule=0 IS the nadir: convergence at nadirC', mechanization: 'Lean theorem `skyrms_nadir_is_bule_zero` in `SkyrmsNadirBule.lean` (seven-part conjunction)', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_skyrms_nadir_bule_model': { theorem: 'THM-SKYRMS-NADIR-BULE-MODEL', claim: 'Model-checked equivalence of three-walker convergence and Bule convergence: Bule nonneg, bounded, nadir constant, community tracks rounds, attenuation = convergence, algebraic nadir correct, solve-don', mechanization: 'TLA+ `SkyrmsNadirBule.tla` + `SkyrmsNadirBule.cfg` with 8 invariants and 4 temporal properties', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_diversity_optimality': { theorem: 'THM-DIVERSITY-OPTIMALITY', claim: 'Composition theorem: diversity is the monotonically optimal, thermodynamically necessary condition for information-preserving computation in fork/race/fold systems. Five pillars: (1) Monotonicity — ad', mechanization: 'TLA+ `DiversityOptimality.tla` invariants `InvMonotonicity`, `InvSubsumption`, `InvNecessity`, `InvOptimality`, `InvIrreversibility`, `InvDiversityOpt', section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)' },
  'thm_rejection_gradient': { theorem: 'THM-REJECTION-GRADIENT', claim: 'Rejection-driven policy gradient is well-defined: all weights > 0', mechanization: '`NovelInference.lean:rejection_gradient_well_defined` via `buleyean_positivity`', section: 'Novel Inference Forms (§19.21)' },
  'thm_rejection_data_advantage': { theorem: 'THM-REJECTION-DATA-ADVANTAGE', claim: 'Rejection provides (N-1)x more data than reward', mechanization: '`NovelInference.lean:rejection_data_advantage` via `failure_data_dominates`', section: 'Novel Inference Forms (§19.21)' },
  'thm_rejection_exploration': { theorem: 'THM-REJECTION-EXPLORATION', claim: 'Rejection RL preserves exploration (sliver)', mechanization: '`NovelInference.lean:rejection_preserves_exploration` via `the_sliver`', section: 'Novel Inference Forms (§19.21)' },
  'thm_rejection_concentration': { theorem: 'THM-REJECTION-CONCENTRATION', claim: 'Gradient concentrates on least-rejected actions', mechanization: '`NovelInference.lean:rejection_gradient_concentrates` via `buleyean_concentration`', section: 'Novel Inference Forms (§19.21)' },
  'thm_beta1_compute_monotone': { theorem: 'THM-BETA1-COMPUTE-MONOTONE', claim: 'Higher beta-1 -> more compute allocated', mechanization: '`NovelInference.lean:beta1_compute_monotone`', section: 'Novel Inference Forms (§19.21)' },
  'thm_minimum_compute': { theorem: 'THM-MINIMUM-COMPUTE', claim: 'Every token gets >= 1 layer', mechanization: '`NovelInference.lean:minimum_compute_guarantee`', section: 'Novel Inference Forms (§19.21)' },
  'thm_total_compute_bounded': { theorem: 'THM-TOTAL-COMPUTE-BOUNDED', claim: 'Total compute bounded by N x (maxBeta1 + 1)', mechanization: '`NovelInference.lean:total_compute_bounded`', section: 'Novel Inference Forms (§19.21)' },
  'thm_certain_token_minimal': { theorem: 'THM-CERTAIN-TOKEN-MINIMAL', claim: 'Zero-beta-1 token gets exactly 1 layer', mechanization: '`NovelInference.lean:certain_token_minimal_compute`', section: 'Novel Inference Forms (§19.21)' },
  'thm_void_cache_smaller': { theorem: 'THM-VOID-CACHE-SMALLER', claim: 'Void cache <= full KV cache when d_model >= 2', mechanization: '`NovelInference.lean:void_cache_smaller`', section: 'Novel Inference Forms (§19.21)' },
  'thm_void_cache_reconstructs': { theorem: 'THM-VOID-CACHE-RECONSTRUCTS', claim: 'Same rejection counts -> same complement weights', mechanization: '`NovelInference.lean:void_cache_reconstructs` via `buleyean_coherence`', section: 'Novel Inference Forms (§19.21)' },
  'thm_void_cache_update': { theorem: 'THM-VOID-CACHE-UPDATE', claim: 'Adding one rejection is O(1)', mechanization: '`NovelInference.lean:void_cache_monotone_update`', section: 'Novel Inference Forms (§19.21)' },
  'thm_void_cache_positive': { theorem: 'THM-VOID-CACHE-POSITIVE', claim: 'All dimensions retain positive weight', mechanization: '`NovelInference.lean:void_cache_positive` via `buleyean_positivity`', section: 'Novel Inference Forms (§19.21)' },
  'thm_free_energy_decreasing': { theorem: 'THM-FREE-ENERGY-DECREASING', claim: 'Computing one layer reduces free energy by 1', mechanization: '`NovelInference.lean:free_energy_decreasing`', section: 'Novel Inference Forms (§19.21)' },
  'thm_exit_eventually_reached': { theorem: 'THM-EXIT-EVENTUALLY-REACHED', claim: 'Free energy reaches zero at totalLayers', mechanization: '`NovelInference.lean:exit_eventually_reached`', section: 'Novel Inference Forms (§19.21)' },
  'thm_exit_saves_energy': { theorem: 'THM-EXIT-SAVES-ENERGY', claim: 'Remaining = totalLayers - layersComputed', mechanization: '`NovelInference.lean:exit_saves_energy`', section: 'Novel Inference Forms (§19.21)' },
  'thm_exit_deterministic': { theorem: 'THM-EXIT-DETERMINISTIC', claim: 'Same model + same layers computed = same exit', mechanization: '`NovelInference.lean:thermodynamic_exit_deterministic`', section: 'Novel Inference Forms (§19.21)' },
  'thm_inverse_well_defined': { theorem: 'THM-INVERSE-WELL-DEFINED', claim: 'Inverse distribution valid (all positive, total positive)', mechanization: '`NovelInference.lean:inverse_well_defined` via positivity + normalization', section: 'Novel Inference Forms (§19.21)' },
  'thm_inverse_favors_simple': { theorem: 'THM-INVERSE-FAVORS-SIMPLE', claim: 'Least-rejected hypothesis has highest weight', mechanization: '`NovelInference.lean:inverse_favors_simple` via `buleyean_concentration`', section: 'Novel Inference Forms (§19.21)' },
  'thm_inverse_positivity': { theorem: 'THM-INVERSE-POSITIVITY', claim: 'No hypothesis reaches zero probability', mechanization: '`NovelInference.lean:inverse_positivity` via `sliver_irreducible`', section: 'Novel Inference Forms (§19.21)' },
  'thm_novel_inference_master': { theorem: 'THM-NOVEL-INFERENCE-MASTER', claim: 'All five mechanisms compose from three axioms + coherence', mechanization: '`NovelInference.lean:novel_inference_master`', section: 'Novel Inference Forms (§19.21)' }
};
