export type CoverageKind = 'wrapper' | 'semantic' | 'umbrella';

export interface SectionDefault {
  readonly section: string;
  readonly server: string;
  readonly coverageKind?: CoverageKind;
}

export interface OwnershipOverride {
  readonly server: string;
  readonly coverageKind?: CoverageKind;
  readonly toolTheoremId?: string;
}

export const SECTION_DEFAULTS: readonly SectionDefault[] = [
  { section: 'Foundation: Fork/Race/Fold Axioms & Core Laws', server: 'verification-mcp' },
  { section: 'Monoidal Coherence & Traced Structure (Tracks Zeta + Eta)', server: 'coherence-mcp' },
  { section: 'Failure Theory: Collapse, Cost, and Control', server: 'failure-mcp' },
  { section: 'Thermodynamic Bridge: Erasure, Heat, and Information', server: 'thermodynamics-mcp' },
  { section: 'Beauty Optimality', server: 'beauty-mcp' },
  { section: 'Covering Space & Topological Deficit (Track Theta)', server: 'topology-mcp' },
  { section: 'Protocol, Settlement & Band Gap', server: 'protocol-mcp' },
  { section: 'Pipeline Scheduling (Section 7)', server: 'pipeline-mcp' },
  { section: 'Queueing Theory', server: 'queueing-mcp' },
  { section: 'Geometric & Compositional Ergodicity (Tracks Delta + Iota)', server: 'ergodicity-mcp' },
  { section: 'Lyapunov Synthesis (Tracks Kappa + Nu + Xi)', server: 'ergodicity-mcp' },
  { section: 'Envelope Convergence (Track Mu)', server: 'ergodicity-mcp' },
  { section: 'Wallington Rotation Optimality (Track Lambda)', server: 'pipeline-mcp' },
  { section: 'Race Winner Correctness (Track Omicron)', server: 'race-mcp' },
  { section: 'Frame Native Execution', server: 'protocol-mcp' },
  { section: 'Void Walking', server: 'void-walking-mcp' },
  { section: 'Semiotic Deficit & Peace (Track Pi)', server: 'conflict-mcp' },
  { section: 'Negotiation Equilibrium', server: 'negotiation-mcp' },
  { section: 'Void Relativity & Grand Unification', server: 'relativity-mcp' },
  { section: 'Daisy Chain, Glossolalia & MOA', server: 'metacognition-mcp' },
  { section: 'Whip Wave Duality', server: 'protocol-mcp' },
  { section: 'Quorum Protocols', server: 'quorum-mcp' },
  { section: 'Cross-Language Semantic Type Theory', server: 'verification-mcp' },
  { section: 'Gnosis Compiler Proofs', server: 'verification-mcp' },
  { section: 'Interference, Renormalization & Coarsening Synthesis', server: 'coarsening-mcp' },
  { section: 'Community Dominance & Skyrms Nadir', server: 'coarsening-mcp' },
  { section: 'Heterogeneous MoA Fabric', server: 'coarsening-mcp' },
  { section: 'Molecular Topology & Genomics', server: 'genomics-mcp' },
  { section: 'Cancer Topology (§3.17)', server: 'genomics-mcp' },
  { section: 'Cancer Predictions (§19.9)', server: 'genomics-mcp' },
  { section: 'Cancer Predictions Round 3 (§19.9, Predictions 11-15)', server: 'genomics-mcp' },
  { section: 'Cancer Predictions Round 4 (§19.9, Predictions 26-30)', server: 'genomics-mcp' },
  { section: 'Cancer Predictions Round 5 (§19.9, Predictions 31-35)', server: 'genomics-mcp' },
  { section: 'Cancer Treatment Strategies (§19.23, Predictions 76-80)', server: 'genomics-mcp' },
  { section: 'Quantum Cancer Triples (§19.9)', server: 'genomics-mcp' },
  { section: 'Cancer Confinement (§19.9 / §3.17)', server: 'genomics-mcp' },
  { section: 'Quantum Observer', server: 'quantum-mcp' },
  { section: 'Server Optimality & Codec Racing', server: 'race-mcp' },
  { section: 'Self-Hosting Optimality', server: 'void-walking-mcp' },
  { section: 'Humans Are Compilers', server: 'metacognition-mcp' },
  { section: 'Optimality Undecidable', server: 'race-mcp' },
  { section: 'The God Gap', server: 'race-mcp' },
  { section: 'Sliver-Exploration Theorem', server: 'coarsening-mcp' },
  { section: 'The Exploration Identity', server: 'coarsening-mcp' },
  { section: 'Buleyean Spin Pairing', server: 'buleyean-mcp' },
  { section: 'Particles Exist', server: 'quantum-mcp' },
  { section: 'Syzygy', server: 'quantum-mcp' },
  { section: 'Quark Confinement', server: 'quantum-mcp' },
  { section: 'The Ten Bosons: A Gnostic Particle Model', server: 'quantum-mcp' },
  { section: 'Ten-Mode Unification', server: 'quantum-mcp' },
  { section: 'The Gnostic Numbers', server: 'buleyean-mcp' },
  { section: 'Sleep Debt', server: 'sleep-mcp' },
  { section: 'Retrocausal Bound', server: 'quantum-mcp' },
  { section: 'American Frontier', server: 'topology-mcp' },
  { section: 'The Last Question (Asimov Bridge)', server: 'coherence-mcp' },
  { section: 'Chaitin Omega (Computability Bridge)', server: 'coherence-mcp' },
  { section: 'Non-Empirical Prediction (§15.22)', server: 'inference-forms-mcp' },
  { section: 'Grandfather Paradox (§15.23)', server: 'quantum-mcp' },
  { section: 'Five Novel AI Inference Forms (§15.24)', server: 'inference-forms-mcp' },
  { section: 'Novel Cross-Domain Predictions (§19.11)', server: 'inference-forms-mcp' },
  { section: 'Metacognitive Walker & Void Attention', server: 'metacognition-mcp' },
  { section: 'Reynolds BFT', server: 'quorum-mcp' },
  { section: 'Pluralist Republic', server: 'governance-mcp' },
  { section: 'Buleyean Evidence Standards (§28)', server: 'evidence-mcp' },
  { section: 'Predictions Round 8: Memory, Ecology, Supply Chain, Jury, Skill Transfer (§19.27)', server: 'inference-forms-mcp' },
  { section: 'Arrow, Godel, Consciousness (§10.6)', server: 'coherence-mcp' },
  { section: 'Buleyean Pulse Quadrant (§10.6)', server: 'buleyean-mcp' },
  { section: 'Community Compositions (§10.6)', server: 'governance-mcp' },
  { section: 'CMB Visibility Boundary', server: 'quantum-mcp' },
  { section: 'Cosmic Optimal Delta', server: 'quantum-mcp' },
  { section: 'Knowability Split', server: 'quantum-mcp' },
  { section: 'Covering Space Causality (§3.3)', server: 'topology-mcp' },
  { section: 'Cross-File Compositions (§19)', server: 'inference-forms-mcp' },
  { section: 'Cross-Module Identities (§19)', server: 'inference-forms-mcp' },
  { section: 'Deep Compositions (§19)', server: 'inference-forms-mcp' },
  { section: 'Diversity Unwound (§10.6)', server: 'topology-mcp' },
  { section: 'Evolution (§10.6)', server: 'genomics-mcp' },
  { section: 'Failure Controller (§9)', server: 'failure-mcp' },
  { section: 'Failure Pareto (§9)', server: 'failure-mcp' },
  { section: 'Failure Universality (§9)', server: 'failure-mcp' },
  { section: 'Fisher Manifold (§15)', server: 'buleyean-mcp' },
  { section: 'Grand Unification (§10.6)', server: 'relativity-mcp' },
  { section: 'Launch Offset Dominance (§12)', server: 'coarsening-mcp' },
  { section: 'Novel Compositions (§19)', server: 'inference-forms-mcp' },
  { section: 'Novel Predictions Round 28 (§19)', server: 'inference-forms-mcp' },
  { section: 'Post-Linear Transition (§10.6)', server: 'topology-mcp' },
  { section: 'Prediction Proofs Round 1 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 2 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 3 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 4 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 10 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 11 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 14 (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 5 (§19, Predictions 66-70)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 6 (§19, Predictions 71-75)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 7 (§19, Predictions 111-115)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 9 (§19, Predictions 142-146)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 12 (§19, Predictions 177-181)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 13 (§19)', server: 'inference-forms-mcp' },
  { section: 'Adaptive Bisimulation Predictions (§19, Predictions 232-236)', server: 'inference-forms-mcp' },
  { section: 'Hetero Compositional Predictions (§19, Predictions 242-246)', server: 'inference-forms-mcp' },
  { section: 'Complement Oscillation (§15)', server: 'buleyean-mcp' },
  { section: 'Novel Triple Compositions (§19, Predictions 292-296)', server: 'inference-forms-mcp' },
  { section: 'Novel Triple Compositions Round 2 (§19, Predictions 297-301)', server: 'inference-forms-mcp' },
  { section: 'Teleportation Evidence Predictions (§19, Predictions 212-216)', server: 'inference-forms-mcp' },
  { section: 'Triple Compositions (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 15: Sandwich-Derived Statistics (§19)', server: 'inference-forms-mcp' },
  { section: 'Predictions Round 16: Cross-Sandwich Combinatorics (§19)', server: 'inference-forms-mcp' },
  { section: 'Semiotic Triples (§19)', server: 'conflict-mcp' },
  { section: 'Sliver from Vent (§10.6)', server: 'thermodynamics-mcp' },
  { section: 'Sliver of Hope (§10.6)', server: 'buleyean-mcp' },
  { section: 'Statistical Teleportation (§15)', server: 'quantum-mcp' },
  { section: 'Time Travel Topology (§15.23)', server: 'quantum-mcp' },
  { section: 'Trade Topology (§19)', server: 'economics-mcp' },
  { section: 'Trade Topology Round 3 (§19, P212-P216)', server: 'economics-mcp' },
  { section: 'Trade Topology Round 4 (§19, P222-P226)', server: 'economics-mcp' },
  { section: 'Novel Inference Forms (§19.21)', server: 'inference-forms-mcp' },
  { section: 'Floor Theorems: Missing Lower Bounds (§3, §7, §9, §12, §13, §15)', server: 'verification-mcp' },
  { section: 'Five-Parameter Void Walker Personality Model (ch17 section 15.10.7, 15.12)', server: 'metacognition-mcp' },
  { section: 'Buleyean Proof Topology System (ch17 section 20.2.8)', server: 'verification-mcp' },
  { section: 'Buleyean Grand Unification: RL + Logic + Probability = Rejection (ch17 sections 15.10.7, 20.2.8)', server: 'buleyean-mcp' },
  // ── Combinatorial Brute Force (Sections 86-90) ──────────────────────
  { section: 'Combinatorial Brute Force: Cross-Module Compositions (§17+§22+§23)', server: 'inference-forms-mcp' },
  { section: 'Combinatorial Brute Force Round 2: Cross-Domain Compositions (§17+§19+§22+§23)', server: 'inference-forms-mcp' },
  { section: 'Combinatorial Brute Force Round 3: Exotic Cross-Domain (§9+§17+§22+§23)', server: 'inference-forms-mcp' },
  { section: 'Combinatorial Brute Force Round 4: Governance, Physics, and Waste (§7+§9+§11+§25+§26)', server: 'inference-forms-mcp' },
  { section: 'Combinatorial Brute Force Round 5: Deep Quad Compositions and Grand Unification (§7+§9+§11+§17+§22+§23+§25+§26)', server: 'inference-forms-mcp' },
  // ── Philosophical Allegories & Logic (Sections 91-98) ────────────────
  { section: 'Philosophical Allegories: Machine-Checked Ancient Wisdom (§20+§22+§23+§25)', server: 'philosophy-mcp' },
  { section: 'The Greek Logic Canon: Twelve Paradoxes and Mysteries (§20+§22+§23)', server: 'philosophy-mcp' },
  { section: 'Unsolved Mysteries: Fork/Race/Fold Perspectives (§17+§20+§22+§23)', server: 'philosophy-mcp' },
  { section: 'Second Tier Mysteries: How Did They Do That? (§17+§22+§23+§25)', server: 'philosophy-mcp' },
  { section: 'Philosophical Combinatorics: Cross-Allegory Compositions (§15.30)', server: 'philosophy-mcp' },
  { section: 'Philosophical Combinatorics Round 2: Philosophy × Science × Engineering (§15.30)', server: 'philosophy-mcp' },
  { section: 'Philosophical Combinatorics Round 3: Stress-Testing the Limits (§15.30)', server: 'philosophy-mcp' },
  { section: 'Philosophical Combinatorics Round 4: Seven Universal Laws (§15.30)', server: 'philosophy-mcp' },
  // ── Seven Laws Predictions (Sections 99-103) ────────────────────────
  { section: 'Seven Laws Predictions: Wild Novel Predictions (§15.30+§19)', server: 'predictions-mcp' },
  { section: 'Seven Laws Predictions Round 2: Music, Dreams, Humor, Love, and Death (§15.30+§19)', server: 'predictions-mcp' },
  { section: 'Seven Laws Predictions Round 3: Consciousness, Mastery, Teaching, and the Universe (§15.30+§19)', server: 'predictions-mcp' },
  { section: 'Seven Laws Predictions Round 4: Game Theory, Economics, Ecology, Ethics (§15.30+§19)', server: 'predictions-mcp' },
  { section: 'Seven Laws Predictions Round 5: The Grand Finale (§15.30+§19)', server: 'predictions-mcp' },
  // ── Hard Compositions (Section 104) ──────────────────────────────────
  { section: 'Hard Compositions: Real Analysis Territory (§15.30)', server: 'ergodicity-mcp' },
  // ── God Formula & Reduction (Sections 105-111) ───────────────────────
  { section: 'Surface Reduction: The Minimal Generating Set (§15.30.3)', server: 'god-formula-mcp' },
  { section: 'Deep Reduction: From Seven Laws to One Axiom (§15.30.3)', server: 'god-formula-mcp' },
  { section: 'The Primator: The Final Reduction (§15.30.3)', server: 'god-formula-mcp' },
  { section: 'The Ceiling: What the Framework Cannot Prove (§15.30.3)', server: 'god-formula-mcp' },
  { section: 'The Gain: The Habitable Zone Between Floor and Ceiling (§15.30.3)', server: 'god-formula-mcp' },
  { section: 'The Control Statistic: Validating the Sandwich (§15.30.5)', server: 'god-formula-mcp' },
  { section: 'The God Formula (§15.30)', server: 'god-formula-mcp' },
] as const;

// Paper-label rows are metadata about an already-owned theorem family.
// They must keep a distinct canonical theorem ID while reusing the base tool
// through `toolTheoremId`, so the audit can record an exact row->tool mapping
// without recreating wrappers or reintroducing duplicate theorem IDs.
export const THEOREM_OVERRIDES: Readonly<Record<string, OwnershipOverride>> = {
  'THM-CONVERGENCE-SCHEMA-PAPER-LABEL': {
    server: 'verification-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-CONVERGENCE-SCHEMA',
  },
  'THM-COMPLETENESS-DAG-PAPER-LABEL': {
    server: 'verification-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-COMPLETENESS-DAG',
  },
  'THM-QUEUE-CONTAINMENT-PAPER-LABEL': {
    server: 'queueing-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-QUEUE-CONTAINMENT',
  },
  'THM-QUEUE-SUBSUMPTION-PAPER-LABEL': {
    server: 'queueing-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-QUEUE-SUBSUMPTION',
  },
  'THM-QUEUE-LIMIT-SCHEMA-PAPER-LABEL': {
    server: 'queueing-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-QUEUE-LIMIT-SCHEMA',
  },
  'THM-QUEUE-STATE-DEPENDENT-SCHEMA-PAPER-LABEL': {
    server: 'queueing-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-QUEUE-STATE-DEPENDENT-SCHEMA',
  },
  'THM-QUEUE-ADAPTIVE-SUPREMUM-PAPER-LABEL': {
    server: 'queueing-mcp',
    coverageKind: 'semantic',
    toolTheoremId: 'THM-QUEUE-ADAPTIVE-SUPREMUM',
  },
  'THM-RG-FIXED-POINTS': { server: 'coarsening-mcp' },
  'THM-THERMO-TRACED-MONOIDAL': { server: 'coherence-mcp' },
  'THM-FOLD-HEAT-HIERARCHY': { server: 'thermodynamics-mcp' },
  'THM-SEMIOTIC-PEACE': { server: 'conflict-mcp' },
  'THM-COMMUNITY-ATTENUATES-FAILURE': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-MONOTONE-NONDEGRADATION': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-STRICT-DOMINATION': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-BRIDGES-TARES': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-BULE-CONVERGENCE': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-DOMINANCE-THEORY': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-DOMINANCE-MODEL': { server: 'coarsening-mcp' },
  'THM-COMMUNITY-IS-SKYRMS-WALKER': { server: 'coarsening-mcp' },
  'THM-BULE-ZERO-IS-NADIR': { server: 'coarsening-mcp' },
  'THM-NADIR-ALGEBRAIC': { server: 'coarsening-mcp' },
  'THM-SKYRMS-NADIR-IS-BULE-ZERO': { server: 'coarsening-mcp' },
  'THM-SKYRMS-NADIR-BULE-MODEL': { server: 'coarsening-mcp' },
  'THM-DIVERSITY-OPTIMALITY': { server: 'coarsening-mcp' },
};
